@startuml
class Mundial.EtapaMundial {
- String descripcionEtapa
- ArrayList<Mundial.Partido> partidos
+ <<Create>> Mundial.EtapaMundial()
+ void addPartido(Mundial.Partido)
+ String getDescripcionEtapa()
# ArrayList<Mundial.Partido> getPartidos()
+ ArrayList<Mundial.Equipo> getEquiposQueAvanzan()
}
@enduml