@startuml
class Partido {
- Date fecha
- Equipo local
- Equipo visitante
- Resultado resultado
+ <<Create>> Partido(Date,Equipo,Equipo,Resultado)
+ Resultado getResultado()
+ Equipo getLocal()
+ Equipo getVisitante()
}
@enduml