@startuml
class Mundial.Partido {
- Date fecha
- Mundial.Equipo local
- Mundial.Equipo visitante
- Mundial.Resultado resultado
+ <<Create>> Mundial.Partido(Date,Mundial.Equipo,Mundial.Equipo,Mundial.Resultado)
+ Mundial.Resultado getResultado()
+ Mundial.Equipo getLocal()
+ Mundial.Equipo getVisitante()
+ void setEquipo(Mundial.EtapaMundial)
}
@enduml