@startuml
class Mundial.Equipo {
- String nombre
- ArrayList<Mundial.Partido> partidosJugados
+ String getNombre()
+ void setNombre(String)
}
class Mundial.EtapaMundial {
- String descripcionEtapa
- ArrayList<Mundial.Partido> partidos
+ <<Create>> Mundial.EtapaMundial()
+ String getDescripcionEtapa()
+ void addPartido(Mundial.Partido)
# ArrayList<Mundial.Partido> getPartidos()
+ ArrayList<Mundial.Equipo> getEquiposQueAvanzan()
}
class Mundial.Llave {
+ ArrayList<Mundial.Equipo> getEquiposQueAvanzan()
}
class Main {
+ {static} void main(String[])
}
class Mundial.Partido {
- Date fecha
- Mundial.Equipo local
- Mundial.Equipo visitante
- Mundial.Resultado resultado
+ <<Create>> Mundial.Partido(Date,Mundial.Equipo,Mundial.Equipo,Mundial.Resultado)
+ Mundial.Resultado getResultado()
+ Mundial.Equipo getLocal()
+ Mundial.Equipo getVisitante()
+ void setEquipo(Mundial.EtapaMundial)
}
class Mundial.Resultado {
- int golesLocales
- int golesVisitante
+ int getGolesLocales()
+ int getGolesVisitante()
+ boolean ganoLocal()
+ boolean empate()
}
class Mundial.Grupo {
+ ArrayList<Mundial.Equipo> getEquiposQueAvanzan()
}
@enduml